services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ai-bot
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - shared-network

networks:
  shared-network:
    external: True