"""remove category model

Revision ID: 4ba0346d7e2d
Revises: 191cf28f7756
Create Date: 2026-02-15 13:42:20.147502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ba0346d7e2d'
down_revision: Union[str, Sequence[str], None] = '191cf28f7756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aicategories')
    op.add_column('aimodels', sa.Column('aicategory', sa.String(), nullable=True))
    # op.drop_constraint(op.f('aimodels_aicategory_id_fkey'), 'aimodels', type_='foreignkey')
    op.drop_column('aimodels', 'aicategory_id')
    op.add_column('messages', sa.Column('correct', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'correct')
    op.add_column('aimodels', sa.Column('aicategory_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # op.create_foreign_key(op.f('aimodels_aicategory_id_fkey'), 'aimodels', 'aicategories', ['aicategory_id'], ['id'], ondelete='CASCADE')
    op.drop_column('aimodels', 'aicategory')
    op.create_table('aicategories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('alias', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('aicategories_pkey'))
    )
    # ### end Alembic commands ###
